version: '3'

services:
  postgres2:
    image: postgres:12
    volumes:
    - db_data2:/var/lib/postgresql/data
    ports:
    - 6789:5432
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: password

  hasura:
    image: hasura/graphql-engine:v2.3.0
    ports:
    - 6060:8080
    depends_on:
    - postgres2
    environment:
      VIRTUAL_HOST: test.dashboard.smartnanumi.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: test.dashboard.smartnanumi.com
      LETSENCRYPT_EMAIL: smartnanumi@kakao.com
      HASURA_GRAPHQL_DATABASE_URL: postgres://dashboard:password@postgres2/dashboard
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: sm@Rtn@Num!
      # HASURA_GRAPHQL_JWT_SECRET: |-
      #   {
      #     "jwk_url": "https://auth.airsmed.io/auth/realms/webdemo/protocol/openid-connect/certs",
      #     "issuer": "https://auth.airsmed.io/auth/realms/webdemo",
      #     "allowed_skew": 30
      #   }
    networks:
      - nginx-proxy
      - default

volumes:
  db_data2:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
